pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp index.html public/
    - cp manifest.json sw.js public/
    - cp -r css js icons public/
  artifacts:
    paths:
      - public
  only:
    - main
